import uuid
from sqlalchemy import Column, String, Integer, ForeignKey, Index
from sqlalchemy.orm import relationship
from backend.app.database.base import Base


def _generate_uuid() -> str:
    return str(uuid.uuid4())


class FindingEvidence(Base):
    """Structured evidence record linked to a Finding.

    One Finding may have many FindingEvidence rows — one per affected
    location or observation.  Evidence is produced exclusively by the
    deterministic analyzers; it is never generated by the AI layer.
    """
    __tablename__ = 'finding_evidence'

    id = Column(String(36), primary_key=True, default=_generate_uuid)

    # Foreign key to the parent Finding.  Cascade delete keeps the DB clean.
    finding_id = Column(
        String(36),
        ForeignKey('findings.id', ondelete='CASCADE'),
        nullable=False,
        index=True,
    )

    # Mirror of the parent Finding.category for efficient filtering without a join.
    category = Column(String(100), nullable=False, default='')

    # Repo-relative path of the file where evidence was found.
    # Empty string for project-level (non-file-specific) evidence.
    source_file = Column(String(500), nullable=False, default='')

    # Line number when the evidence was directly observed at a specific line.
    # Null for absence findings, ratio checks, or file-count checks.
    source_line = Column(Integer, nullable=True)

    # Evidence type: FILE_MATCH | PATTERN_MATCH | AST_NODE | ABSENCE |
    #               FILE_COUNT | RATIO | CONFIG_CHECK
    evidence_type = Column(String(50), nullable=False)

    # Human-readable description of what was found.
    # Secrets must be masked before this field is populated.
    evidence_summary = Column(String(1000), nullable=False)

    # Confidence in the evidence: HIGH | MEDIUM | LOW
    confidence = Column(String(20), nullable=False, default='MEDIUM')

    # Verification status:
    #   OBSERVED   - directly detected from repository evidence.
    #   INFERRED   - derived from observed items but not a single direct fact.
    #   UNVERIFIED - pattern matched but insufficient evidence to confirm.
    verification_status = Column(String(20), nullable=False, default='OBSERVED')

    # Deterministic finding key (mirror of parent Finding.finding_key) so
    # evidence remains traceable even if titles are not unique.
    finding_key = Column(String(300), nullable=True, index=True)

    # Back-reference to the parent Finding.
    finding = relationship('Finding', back_populates='evidence_items')


# Additional index on source_file for file-tree queries.
Index('ix_finding_evidence_source_file', FindingEvidence.source_file)
