from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from backend.app.database.session import get_db
from backend.app.models.findings import Finding
from backend.app.models.evidence import FindingEvidence
from backend.app.schemas.evidence import EvidenceItemSchema

router = APIRouter()


@router.get(
    "/analysis/{analysis_id}/findings/{finding_id}/evidence",
    response_model=List[EvidenceItemSchema],
    summary="Get structured evidence for a specific finding",
    description=(
        "Returns all structured evidence items attached to a finding. "
        "Evidence is produced exclusively by the deterministic analyzers; "
        "it is never generated by the AI layer."
    ),
)
def get_finding_evidence(
    analysis_id: str,
    finding_id: str,
    db: Session = Depends(get_db),
) -> List[EvidenceItemSchema]:
    # Verify the finding belongs to the analysis (prevents ID enumeration).
    finding = (
        db.query(Finding)
        .filter(Finding.id == finding_id, Finding.analysis_id == analysis_id)
        .first()
    )
    if not finding:
        raise HTTPException(
            status_code=404,
            detail=f"Finding '{finding_id}' not found in analysis '{analysis_id}'",
        )

    ev_rows = (
        db.query(FindingEvidence)
        .filter(FindingEvidence.finding_id == finding_id)
        .all()
    )

    return [
        EvidenceItemSchema(
            id=ev.id,
            finding_id=ev.finding_id,
            category=ev.category,
            source_file=ev.source_file,
            source_line=ev.source_line,
            evidence_type=ev.evidence_type,
            evidence_summary=ev.evidence_summary,
            confidence=ev.confidence,
            verification_status=ev.verification_status,
        )
        for ev in ev_rows
    ]
